# Generated by Django 3.2.8 on 2021-10-27 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=40)),
                ('state_region', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=30)),
                ('occupation', models.CharField(blank=True, max_length=25, null=True)),
                ('education', models.CharField(blank=True, max_length=50, null=True)),
                ('bio', models.CharField(blank=True, max_length=1000, null=True)),
                ('religion', models.CharField(blank=True, max_length=25, null=True)),
                ('hobbies', models.CharField(blank=True, max_length=250, null=True)),
                ('dietary_preferences', models.CharField(blank=True, max_length=100, null=True)),
                ('alcohol', models.BooleanField(blank=True, null=True)),
                ('smoking', models.BooleanField(blank=True, null=True)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
    ]
