# Generated by Django 3.2.8 on 2021-11-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoveAajKalApp', '0004_profile_matched'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sexuality',
            field=models.CharField(max_length=25),
        ),
    ]
