# Generated by Django 3.2.8 on 2021-11-16 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoveAajKalApp', '0010_auto_20211116_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='middle_name',
        ),
    ]
