# Generated by Django 3.2.8 on 2021-12-03 06:20

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoveAajKalApp', '0014_alter_profile_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthdate',
            field=models.DateField(default=datetime.date(1900, 1, 1), validators=[django.core.validators.MinValueValidator(datetime.date(1900, 1, 1)), django.core.validators.MaxValueValidator(datetime.date(2003, 12, 3))]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='matched_with',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
