# Generated by Django 3.2.8 on 2021-12-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoveAajKalApp', '0016_alter_profile_matched_with'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='matched_with',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
